// Package vi provides PS2-accurate struct definitions and parsers for
// EQOA's VI engine objects. Every struct layout, field type, and parser
// method is derived from PS2 MIPS binary execution traces, matching the
// original SOE code byte-for-byte.
//
// This package is auto-generated by esf-transpile from MIPS interpreter
// traces of the PS2 SUPPORT module parser functions. Do not hand-edit —
// regenerate from PS2 traces instead.
//
// Architecture:
//
//	PS2 SUPPORT_code.bin → MIPS interpreter → read trace → vi package
//
// The vi package mirrors the PS2 VI engine class hierarchy:
//
//	VIPrimBuffer  → PrimBuffer mesh data (vertices, UVs, normals, colors)
//	VICollBuffer  → Collision mesh (positions, vertex groups, flora types)
//	VICSprite     → Character model (skeleton, animations, equipment)
//	VIHSpriteAnim → Skeletal animation (keyframes, bone tracks)
//	VIScene       → Scene graph (sprites, actors, zones)
//
// Each type has a Parse*() function that reads ESF data in the exact
// same order as the PS2 binary, verified by the MIPS interpreter.
package vi
