// Code generated by esf-transpile --vi from PS2 ParseHSpriteAnimObj.
// Refined from PS2 decompilation at SUPPORT 0x00436560.
//
// This parser is byte-accurate against the PS2 MIPS binary.
package vi

import (
	"encoding/binary"
	"fmt"
)

// VIHSpriteAnim matches the PS2 VIHSpriteAnim struct layout.
// Parsed by ParseHSpriteAnimObj at SUPPORT 0x00436560.
//
// PS2 read sequence (from decompilation + MIPS trace):
//
//	ReadBegin(0x2600)
//	if ver > 1: uint32 dictID             (sp+0x40)
//	int32 format                          (sp+0x44)
//	int32 numNodes                        (sp+0x48)
//	int32 numFrames                       (sp+0x4c)
//	if ver >= 3: int32 numKeyframes       (sp+0x50)
//	float32 fps                           (sp+0x54)
//	if ver >= 1: float32 playSpeed        (sp+0x58)
//	if ver >= 1: int32 playbackType       (sp+0x5c)
//	per node (numNodes iterations):
//	  int32 refID                         (sp+0x68) → SetNodeRefID
//	  per frame (numFrames iterations):
//	    format 0: 8×float32 (pos.xyz, quat.xyzw, scale) → SetNodeFrame(VIHSpriteFrame)
//	    format 1: 8×int16 → SetNodeFrame(VIHSpritePackFrame)
//	    format 2: 8×int16 (packed with float scale conversion)
type VIHSpriteAnim struct {
	DictID       uint32
	Format       int32   // 0=float, 1=packed int16, 2=packed+scaled
	NumNodes     int32   // bone count
	NumFrames    int32   // frames per animation
	NumKeyframes int32   // keyframe count (ver >= 3 only)
	FPS          float32
	PlaySpeed    float32
	PlaybackType int32   // 0=loop, 1=once, etc.

	// Per-node reference IDs (bone hierarchy references)
	NodeRefIDs []int32

	// Per-node frame data: Frames[node][frame]
	Frames [][]VIAnimFrame
}

// VIAnimFrame is one frame of animation data for one node.
type VIAnimFrame struct {
	PosX, PosY, PosZ    float32 // translation
	QuatX, QuatY, QuatZ float32 // rotation quaternion (xyz)
	QuatW               float32 // rotation quaternion (w)
	Scale               float32 // uniform scale
}

// HSpriteAnim type code
const (
	TypeHSpriteAnim = 0x2600
)

// ParseHSpriteAnim reads an HSpriteAnim from raw ESF object data.
// data starts at the ESF object header (type + ver + size).
func ParseHSpriteAnim(data []byte) (*VIHSpriteAnim, error) {
	if len(data) < 8 {
		return nil, fmt.Errorf("VIHSpriteAnim: data too short (%d bytes)", len(data))
	}

	typ := binary.LittleEndian.Uint16(data[0:])
	ver := binary.LittleEndian.Uint16(data[2:])

	if typ != TypeHSpriteAnim {
		return nil, fmt.Errorf("VIHSpriteAnim: wrong type 0x%04X", typ)
	}

	anim := &VIHSpriteAnim{}
	pos := 8 // past header

	// PS2: ver > 1 reads dictID (sltiu $v0, ver, 2)
	if ver > 1 {
		anim.DictID = ru32(data, &pos) // sp+0x40
	}

	// Three unconditional int32 reads
	anim.Format = ri32(data, &pos)    // sp+0x44
	anim.NumNodes = ri32(data, &pos)  // sp+0x48
	anim.NumFrames = ri32(data, &pos) // sp+0x4c

	// PS2: ver >= 3 reads numKeyframes (sltiu $v0, ver, 3)
	if ver >= 3 {
		anim.NumKeyframes = ri32(data, &pos) // sp+0x50
	}

	anim.FPS = rf32(data, &pos) // sp+0x54

	// PS2: ver >= 1 reads playSpeed + playbackType
	// (ObjectVersion check == 0 means ver==0 → skip)
	if ver >= 1 {
		anim.PlaySpeed = rf32(data, &pos)    // sp+0x58
		anim.PlaybackType = ri32(data, &pos) // sp+0x5c
	} else {
		anim.PlaySpeed = 1.0 // PS2 default: li $at, 0x3F800000; mtc1 $at, $f0
	}

	// Sanity checks
	if anim.NumNodes < 0 || anim.NumNodes > 1000 {
		return nil, fmt.Errorf("VIHSpriteAnim: invalid numNodes %d", anim.NumNodes)
	}
	if anim.NumFrames < 0 || anim.NumFrames > 100000 {
		return nil, fmt.Errorf("VIHSpriteAnim: invalid numFrames %d", anim.NumFrames)
	}

	anim.NodeRefIDs = make([]int32, anim.NumNodes)
	anim.Frames = make([][]VIAnimFrame, anim.NumNodes)

	for n := int32(0); n < anim.NumNodes; n++ {
		// PS2: per-node refID (sp+0x68) → SetNodeRefID
		anim.NodeRefIDs[n] = ri32(data, &pos)

		anim.Frames[n] = make([]VIAnimFrame, anim.NumFrames)

		for f := int32(0); f < anim.NumFrames; f++ {
			fr := &anim.Frames[n][f]

			switch anim.Format {
			case 0:
				// Float format: 8×ReadFloat32 per frame
				if pos+32 > len(data) { break }
				fr.PosX = rf32(data, &pos)
				fr.PosY = rf32(data, &pos)
				fr.PosZ = rf32(data, &pos)
				fr.QuatX = rf32(data, &pos)
				fr.QuatY = rf32(data, &pos)
				fr.QuatZ = rf32(data, &pos)
				fr.QuatW = rf32(data, &pos)
				fr.Scale = rf32(data, &pos)

			case 1, 2:
				// Packed int16 format: 8×ReadInt16 per frame
				// PS2: SetNodeFrame with VIHSpritePackFrame (format 1)
				// or float conversion (format 2) — both read 8×int16
				if pos+16 > len(data) { break }
				fr.PosX = float32(ri16(data, &pos)) / 512.0
				fr.PosY = float32(ri16(data, &pos)) / 512.0
				fr.PosZ = float32(ri16(data, &pos)) / 512.0
				fr.QuatX = float32(ri16(data, &pos)) / 32767.0
				fr.QuatY = float32(ri16(data, &pos)) / 32767.0
				fr.QuatZ = float32(ri16(data, &pos)) / 32767.0
				fr.QuatW = float32(ri16(data, &pos)) / 32767.0
				fr.Scale = float32(ri16(data, &pos)) / 32767.0

			default:
				return nil, fmt.Errorf("VIHSpriteAnim: unsupported format %d", anim.Format)
			}
		}
	}

	_ = ver
	return anim, nil
}
