// Code generated by esf-transpile --vi from PS2 ParseCollBuffer.
// DO NOT EDIT — regenerate with: esf-transpile --vi --type 0x4200 [esf-files...]
//
// This parser is byte-accurate against the PS2 MIPS binary.
// Every read type and order matches the native PS2 execution trace.
package vi

import (
	"encoding/binary"
	"fmt"
	"math"
)

// VICollBuffer matches the PS2 VICollBuffer struct layout.
// Parsed by ParseCollBuffer at SUPPORT 0x004343D8.
//
// PS2 read sequence (from MIPS interpreter trace):
//
//	ReadBegin(0x4200)
//	if ver > 1: int32 cbtype (VICollBufferType)
//	int32 numPrimGroups
//	int32 numVertexGroups (face/strip count)
//	int32 unk
//	if ver >= 2: int32 packing
//	per vertex group:
//	  int32 nverts
//	  int32 primGroup
//	  int32 list
//	  per vertex (type-dependent):
//	    type 0: 3×float32
//	    type 1: 3×int16
//	    type 2: 3×int16 + int16(vgroup, truncated to int8)
//	    type 3: 3×int16 + int16(vgroup) + int16(flora) [PS2 reads int16, uses as signed byte]
type VICollBuffer struct {
	Type            int32 // VICollBufferType enum
	NumPrimGroups   int32
	NumVertexGroups int32
	Packing         int32 // scale = 1 / pow(2, Packing)

	Faces []VICollFace
}

// VICollFace is one triangle strip in the CollBuffer.
type VICollFace struct {
	Vertices []VICollVertex
}

// VICollVertex is a single collision vertex.
type VICollVertex struct {
	X, Y, Z     float32
	VertexGroup int8 // -1 if not present (type 0/1)
	FloraType   int8 // -1 if not present (type 0/1/2)
}

// CollBuffer type codes
const (
	TypeCollBuffer = 0x4200
)

// VICollBufferType enum matching PS2
const (
	CollTypeFloat     = 0 // 3×float32 per vertex
	CollTypePacked    = 1 // 3×int16 per vertex
	CollTypePackedVG  = 2 // 3×int16 + vgroup(int16→int8) per vertex
	CollTypePackedVGF = 3 // 3×int16 + vgroup(int16→int8) + flora(int16→int8) per vertex
)

// ParseCollBuffer reads a CollBuffer from raw ESF object data.
// data starts at the ESF object header (type + ver + size).
// Verified against PS2 MIPS execution (18 objects traced).
func ParseCollBuffer(data []byte) (*VICollBuffer, error) {
	if len(data) < 8 {
		return nil, fmt.Errorf("VICollBuffer: data too short (%d bytes)", len(data))
	}

	typ := binary.LittleEndian.Uint16(data[0:])
	ver := binary.LittleEndian.Uint16(data[2:])

	if typ != TypeCollBuffer {
		return nil, fmt.Errorf("VICollBuffer: wrong type 0x%04X", typ)
	}

	cb := &VICollBuffer{}
	pos := 8 // past header

	// PS2: version > 1 reads cbtype
	if ver > 1 {
		cb.Type = ri32(data, &pos)
	}

	cb.NumPrimGroups = ri32(data, &pos)
	cb.NumVertexGroups = ri32(data, &pos)
	_ = ri32(data, &pos) // unk

	// PS2: version >= 2 reads packing
	if ver >= 2 {
		cb.Packing = ri32(data, &pos)
	}

	// Packing scale factor (PS2: powf(2.0, packing) then 1.0/result)
	pk := float32(1.0 / math.Pow(2, float64(cb.Packing)))

	// Sanity check
	if cb.NumVertexGroups < 0 || cb.NumVertexGroups > 10000 {
		return nil, fmt.Errorf("VICollBuffer: invalid numVertexGroups %d", cb.NumVertexGroups)
	}

	cb.Faces = make([]VICollFace, 0, cb.NumVertexGroups)

	for fi := int32(0); fi < cb.NumVertexGroups; fi++ {
		if pos+12 > len(data) {
			break
		}
		nverts := ri32(data, &pos)
		_ = ri32(data, &pos) // primGroup
		_ = ri32(data, &pos) // list

		if nverts > 100000 {
			break
		}
		if nverts <= 0 {
			cb.Faces = append(cb.Faces, VICollFace{})
			continue
		}

		face := VICollFace{
			Vertices: make([]VICollVertex, 0, nverts),
		}

		for vi := int32(0); vi < nverts; vi++ {
			var v VICollVertex
			v.VertexGroup = -1
			v.FloraType = -1

			switch cb.Type {
			case CollTypeFloat:
				if pos+12 > len(data) { break }
				v.X = rf32(data, &pos)
				v.Y = rf32(data, &pos)
				v.Z = rf32(data, &pos)

			case CollTypePacked:
				if pos+6 > len(data) { break }
				v.X = float32(ri16(data, &pos)) * pk
				v.Y = float32(ri16(data, &pos)) * pk
				v.Z = float32(ri16(data, &pos)) * pk

			case CollTypePackedVG:
				// PS2: 4×ReadInt16, 4th truncated to signed byte for vgroup
				if pos+8 > len(data) { break }
				v.X = float32(ri16(data, &pos)) * pk
				v.Y = float32(ri16(data, &pos)) * pk
				v.Z = float32(ri16(data, &pos)) * pk
				v.VertexGroup = int8(ri16(data, &pos))

			case CollTypePackedVGF:
				// PS2: 3×ReadInt16 + ReadSChar(vgroup) + ReadSChar(flora)
				// PS2 uses Read__9VIObjFileRSc (signed char) for both
				if pos+8 > len(data) { break }
				v.X = float32(ri16(data, &pos)) * pk
				v.Y = float32(ri16(data, &pos)) * pk
				v.Z = float32(ri16(data, &pos)) * pk
				v.VertexGroup = ri8(data, &pos)
				v.FloraType = ri8(data, &pos)

			default:
				return nil, fmt.Errorf("VICollBuffer: unsupported type %d", cb.Type)
			}

			face.Vertices = append(face.Vertices, v)
		}

		cb.Faces = append(cb.Faces, face)
	}

	return cb, nil
}
// Read helpers ri32, rf32, ri16, ri8 are defined in parse_primbuffer.go
